### ISSUE TITLE
Migrate from Segment v1 -> v2

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/frontend-platform#418]
# Context

We currently inject `v1` of the Segment.js script in the `SegmentAnalyticsService` for micro-frontends:

https://github.com/openedx/frontend-platform/blob/26f1f306bdb431152f036f3cf5a98c8b111d665a/src/analytics/SegmentAnalyticsService.js#L96

However, v1 of the Segment.js script is deprecated and will automatically cutover to v2 at the end of February 2023 ([docs](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/ajs-classic/)).

<img width="713" alt="image" src="https://user-images.githubusercontent.com/2828721/209206396-7aa35f16-4bb7-4e9c-9c69-0499bb0d79db.png">

Migration Guide from Segment: https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/

# Acceptance Criteria
* Understand the impacts of moving our Segment.js from v1 to v2 for consuming MFEs, if any.
* Ensure `@edx/frontend-platform` and its consuming MFEs are compatible with the the v2 Segment.js snippet.

**Comment by ishahroz** [comment]
Hi @adamstankiewicz, I worked on this `Segment` analytics migration issue. Following is the progress report:

- As per what is required, I updated `Analytics.js` to `v2.0` via `Segment` dashboard for all the available `staging instances` of consuming MFEs of `frontend-platform`. [Here](https://docs.google.com/spreadsheets/d/1UGsGC5KOHj53ak7O15_EuT5ZOFSVgDSqSfcn3j4CXNM/edit?usp=sharing) is the sheet that keeps record for v2.0 status for` frontend-platform` consuming MFEs. In the `Segment v2.0 Staging Status` column, you can see the status for v2.0 upgrade against the consuming MFE. _I updated for those, whose instances were available on the Segment dashboard._ In `Segment v2.0 Staging Status` column, `Not Found` means I found no Segment instance against that MFE (For this, I am reaching out to these MFEs owners squad to inquire if they are not using Segment Analytics at all? So that, I can update the sheet accordingly). I've debugged and tested all the events being triggered from any MFE after upgrading to `v2.0`. **Analytics.js is working fine for staging instances as before.**
- For the next part of process, I am working on upgrading `Analytics.js` to `v2.0` via `Segment` dashboard for all the available `production instances` of consuming MFEs of `frontend-platform`. I will add the `production` status in the [same sheet](https://docs.google.com/spreadsheets/d/1UGsGC5KOHj53ak7O15_EuT5ZOFSVgDSqSfcn3j4CXNM/edit?usp=sharing) and will update the work progress on this issue thread as well. **After this, we may close the issue if nothing else is required.**

Let me know if you have any questions related to the work done so far. Thank you.

**Comment by adamstankiewicz** [comment]
@ishahroz Sounds like a great plan! Thanks for taking this on, your due diligence with reaching out to MFE owners ,and for getting ahead of the issue. Will we need to update the `v1` to `v2` in the URL in the frontend-platform code as well? Presumably, turning `v2.0` on in the Segment dashboard for each Segment source is going to already force it to use `v2.0` regardless of the URL specified here in frontend-platform, but being explicit in the URL probably wouldn't hurt either :)

Thanks for the update!
